//form types
export const SET_FORM_DATA = 'RN_ISAC/form/SET_FORM_DATA';

export const SET_IMAGES_DATA = 'RN_ISAC/form/SET_IMAGES_DATA';

export const SET_FILTERED_IMAGE_DATA = 'RN_ISAC/form/SET_FILTERED_IMAGE_DATA';

export const SET_VIDEO_DATA = 'RN_ISAC/form/SET_VIDEO_DATA';

export const IMAGE_FORM_REQUEST = 'RN_ISAC/form/IMAGE_FORM_REQUEST';
export const IMAGE_FORM_SUCCESS = 'RN_ISAC/form/IMAGE_FORM_SUCCESS';
export const IMAGE_FORM_FAILURE = 'RN_ISAC/form/IMAGE_FORM_FAILURE';

export const VIDEO_FORM_REQUEST = 'RN_ISAC/form/VIDEO_FORM_REQUEST';
export const VIDEO_FORM_SUCCESS = 'RN_ISAC/form/VIDEO_FORM_SUCCESS';
export const VIDEO_FORM_FAILURE = 'RN_ISAC/form/VIDEO_FORM_FAILURE';

export const CLEAR_IMAGE_RESPONSE = 'RN_ISAC/form/CLEAR_IMAGE_RESPONSE';

export const SAVE_REPORT = 'RN_ISAC/form/SAVE_REPORT';

export const GET_OBJECT_TYPE_REQUEST = 'RN_ISAC/form/GET_OBJECT_TYPE_REQUEST';
export const GET_OBJECT_TYPE_SUCCESS = 'RN_ISAC/form/GET_OBJECT_TYPE_SUCCESS';
export const GET_OBJECT_TYPE_FAILURE = 'RN_ISAC/form/GET_OBJECT_TYPE_FAILURE';

export const CROWDSOURCE_FORM_REQUEST = 'RN_ISAC/form/CROWDSOURCE_FORM_REQUEST';
export const CROWDSOURCE_FORM_SUCCESS = 'RN_ISAC/form/CROWDSOURCE_FORM_SUCCESS';
export const CROWDSOURCE_FORM_FAILURE = 'RN_ISAC/form/CROWDSOURCE_FORM_FAILURE';

export const DELETE_CROWDSOURCE_REQUEST =
  'RN_ISAC/form/DELETE_CROWDSOURCE_REQUEST';
export const DELETE_CROWDSOURCE_SUCCESS =
  'RN_ISAC/form/DELETE_CROWDSOURCE_SUCCESS';
export const DELETE_CROWDSOURCE_FAILURE =
  'RN_ISAC/form/DELETE_CROWDSOURCE_FAILURE';

export const SET_EDIT_BOOLEAN = 'RN_ISAC/form/SET_EDIT_BOOLEAN';

export const CLEAR_CROWDSOURCE_FIELD = 'RN_ISAC/form/CLEAR_CROWDSOURCE_FIELD';
