require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'rn_isac' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath],
   # to enable hermes on iOS, change `false` to `true` and then install pods
   :hermes_enabled => false
  )
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'react-native-image-editor', :path => '../node_modules/@react-native-community/image-editor'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  target 'rn_isacTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
    end
end
