export const SET_CURRENT_USER = 'RN_ISAC/auth/SET_CURRENT_USER';

export const SET_SKIP_AUTHENTICATION = 'RN_ISAC/app/SET_SKIP_AUTHENTICATION';

export const SET_USER_DATA = 'RN_ISAC/app/SET_USER_DATA';

export const LOGIN_REQUEST = 'RN_ISAC/auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'RN_ISAC/auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'RN_ISAC/auth/LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'RN_ISAC/auth/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'RN_ISAC/auth/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'RN_ISAC/auth/LOGOUT_FAILURE';

export const REGISTER_REQUEST = 'RN_ISAC/auth/REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'RN_ISAC/auth/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'RN_ISAC/auth/REGISTER_FAILURE';

export const USER_PROFILE_REQUEST = 'RN_ISAC/auth/USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'RN_ISAC/auth/USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'RN_ISAC/auth/USER_PROFILE_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'RN_ISAC/auth/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'RN_ISAC/auth/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'RN_ISAC/auth/FORGOT_PASSWORD_FAILURE';

export const CLEAR_ERROR_DATA = 'RN_ISAC/auth/CLEAR_ERROR_DATA';
